service: backend
provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1
functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-dotenv-plugin
  - serverless-offline
